CREATE DATABASE CASA_MAGAYON;
GO

USE CASA_MAGAYON;
GO

CREATE TABLE USER_ACCOUNT
(
	USER_ID INT PRIMARY KEY NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	[PASSWORD] VARCHAR(20) NOT NULL,
	[ROLE] VARCHAR(20),
	[ADDRESS] VARCHAR(30)
);

CREATE TABLE FEEDBACK(
	FEEDBACK_ID INT PRIMARY KEY NOT NULL,
	FEEDBACK_TYPE BIT NOT NULL,
	DESCRIPTION VARCHAR(MAX) NOT NULL,
	STATUS BIT,
	DATE_SUBMITTED DATETIME DEFAULT GETDATE(),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE SERVICE_REQUEST(
	REQUEST_ID INT PRIMARY KEY NOT NULL,
	REQ_TYPE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(60) NOT NULL,
	STATUS VARCHAR(15),
	DATE_SUBMITTED DATETIME DEFAULT GETDATE(),
	ASSIGNED_STAFF_ID INT,
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE VEHICLE_REGISTRATION(
	VEHICLE_ID INT PRIMARY KEY NOT NULL,
	PLATE_NUMBER VARCHAR(15) NOT NULL,
	TYPE VARCHAR(20),
	[STATUS] VARCHAR(15) NOT NULL,
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE VISITOR_PASSES(
	VISITOR_ID INT PRIMARY KEY NOT NULL,
	VISITOR_NAME VARCHAR(60) NOT NULL,
	DATE_TIME DATETIME DEFAULT GETDATE(),
	[STATUS] VARCHAR(15),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE FACILITY(
	FACILITY_ID INT PRIMARY KEY NOT NULL,
	SCHEDULE DATETIME,
	[STATUS] VARCHAR(10)
)

CREATE TABLE RESERVATIONS(
	RESERVATION_ID INT PRIMARY KEY NOT NULL,
	DATE_TIME DATETIME NOT NULL,
	[STATUS] VARCHAR(10),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID),
	FACILITY_ID INT REFERENCES FACILITY(FACILITY_ID)
)

CREATE TABLE ANNOUNCEMENT(
	ANNOUNCEMENT_ID INT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	[DESCRIPTION] VARCHAR(MAX) NOT NULL,
	DATE_POSTED DATETIME DEFAULT GETDATE(),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE BILL(
	BILL_ID INT PRIMARY KEY NOT NULL,
	DUE_DATE DATE NOT NULL,
	[STATUS] VARCHAR(15) NOT NULL,
)

CREATE TABLE PAYMENT(
	PAYMENT_ID INT PRIMARY KEY NOT NULL,
	AMOUNT_PAID REAL,
	PAYMENT_STATUS BIT,
	PAYMENT_METHOD VARCHAR(20),
	DATE_PAID DATE DEFAULT GETDATE(),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID),
	BILL_ID INT REFERENCES BILL(BILL_ID)
)

CREATE TABLE FORUM(
	POST_ID INT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(60),
	CONTENT VARCHAR(MAX),
	DATE_POSTED DATETIME DEFAULT GETDATE(),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE REPLIES(
	REPLY_ID INT PRIMARY KEY NOT NULL,
	CONTENT VARCHAR(MAX),
	DATE_POSTED DATETIME DEFAULT GETDATE(),
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID),
	POST_ID INT REFERENCES FORUM(POST_ID)
)

CREATE TABLE EVENT_CALENDAR(
	EVENT_ID INT PRIMARY KEY NOT NULL,
	[DESCRIPTION] VARCHAR(200),
	DATE_TIME DATETIME
)

CREATE TABLE POLL(
	POLL_ID INT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(255),
	[DESCRIPTION] VARCHAR(MAX),
	[START_DATE] DATETIME,
	END_DATE DATETIME,
	[STATUS] BIT,
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID)
)

CREATE TABLE POLL_CHOICE(
	CHOICE_ID INT PRIMARY KEY NOT NULL,
	CHOICE VARCHAR(255),
	POLL_ID INT REFERENCES POLL(POLL_ID)
)

CREATE TABLE VOTES(
	VOTE_ID INT PRIMARY KEY NOT NULL,
	VOTE_DATE DATETIME,
	USER_ID INT REFERENCES USER_ACCOUNT(USER_ID),
	POLL_ID INT REFERENCES POLL(POLL_ID),
	CHOICE_ID INT REFERENCES POLL_CHOICE(CHOICE_ID)
)